### ISSUE TITLE
dúvida de implementação

### ISSUE THREAD

**Issue by RuiMartins05** [premium-minds/summer-internship-exercise-2023#1]
Olá,

De forma a otimizar o problema para matrizes de maior tamanho, criei duas threads, uma que descobre a primeira metade do array de acordo com o problema e a segunda que começa do centro para fora até descobrir a sua metade.
Contudo, sei que esta segunda thread pode ir contra o conceito do problema, portanto, pretendia saber se isto é uma solução válida.

Atentamente,
Rui Martins

**Comment by amadoandre** [comment]
Sim todas as soluções são validas desde que explicadas ;)

**Comment by amadoandre** [comment]
Sim todas as soluções são validas desde que explicadas ;)
